config/routes.rb
SchoolMgmt::Application.routes.draw do

  devise_for :users 

  resources :photos

  resources :contacts

  get "imggallery/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :aboutus
  resources :imggallery

  resources :staffs

  
   
  match 'home/about_us' => 'home#about_us'

 resources :class_mstrs
 resources :students
 resources :admin
 resources :adminhome
 resources :users   

 root :to => 'home#index'

 match "/index" =>  'home#index'

end

app/models/aboutu.rb
class Aboutu < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/class_mstr.rb
class ClassMstr < ActiveRecord::Base
  attr_accessible :class_name, :no_of_student, :teacher_name
  validates_presence_of :class_name
  validates_presence_of :teacher_name
  validates_presence_of :no_of_student
 
def self.search(search)
  if search
    where('class_name LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :gmaps, :latitude, :longitude, :name
acts_as_gmappable

  def gmaps4rails_address
   address
  end

  def gmaps4rails_infowindow
   "<h1>#{name}</h1>"
  end


 def gmaps4rails_sidebar
  name
 end

end

app/models/imggallery.rb
class Imggallery < ActiveRecord::Base
   attr_accessible :title, :body, :avatar
   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :name, :avatar

   has_attached_file :avatar, :styles => { :thumb => "100x100>", :large => "400x400>" }
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  attr_accessible :address, :dob, :fname, :lname, :phone

  def self.search(search)
  if search
    where('fname LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :address, :dob, :fname, :lname, :phone, :avatar
  validates_presence_of :fname
  validates_presence_of :lname
  validates_presence_of :address
  validates_presence_of :phone
  validates_presence_of :dob
  
  
  has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "100x100>" }


 def self.search(search)
  if search
    where('fname LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  #  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_role
  # attr_accessible :title, :body

  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

before_filter :authenticate_user!

def index
layout :adminheader  # looks for app/views/layouts/adminheader.html.erb

end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 

  def about_us
   @aboutus = Aboutu.find(:all)
   respond_to do |format|
      format.html # about_us.html.erb
      format.json { render json: @aboutu }
   end
  end 

   def index
    @staff = Staff.find(:all)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @staff }
    end
  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  # before_filter :authenticate_user!
  # GET /staffs
  # GET /staffs.json
  def index

  @staffs = Staff.search(params[:search]).paginate(:per_page => 5,  :page => params[ :page])
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
    @staff = Staff.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/new
  # GET /staffs/new.json
  def new
    @staff = Staff.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/1/edit
  def edit
    @staff = Staff.find(params[:id])
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(params[:staff])

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render json: @staff, status: :created, location: @staff }
      else
        format.html { render action: "new" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /staffs/1
  # PUT /staffs/1.json
  def update
    @staff = Staff.find(params[:id])

    respond_to do |format|
      if @staff.update_attributes(params[:staff])
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy

    respond_to do |format|
      format.html { redirect_to staffs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/adminhome_helper.rb
module AdminhomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_mstrs_helper.rb
module ClassMstrsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imggallery_helper.rb
module ImggalleryHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
 
    <div id="error_explanation" >
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul >
      <% @staff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <table id='tab2' cellpadding='5' align=center>
     <tr><td>First Name</td>
   <td> <%= f.text_field :fname %></td></tr>
  <tr><td>Last Name</td>
   <td> <%= f.text_field :lname %> </td></tr>
 <tr><td>
    <%= f.label :address %></td>
   <td> <%= f.text_field :address %></td></tr>
  <tr>
  <td>
    <%= f.label :phone %></td>
   <td> <%= f.text_field :phone %></td></tr>
  <tr><td>Joining Date</td>
   <td> <%= f.date_select :dob %></td><tr>
 <tr>
 <tr><td colspan='2' align='center'>
  <div class="actions">
    <%= f.submit %>
	</div>
 </td>
 </tr>
 </table>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<h1 align='center'>Listing Staffs poonaaammmmm</h1>
<div align=left>
  <%= form_tag staffs_path, method: :get do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search by name", fname: nil %>
  <% end %>
</div>

<table id='tab' border='1' cellpadding='5' align=center>

  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Joining Date</th>
    <th colspan='3'>Action</th>
  </tr>

<% @staffs.each do |staff| %>
  <tr>
    <td><%= staff.fname %></td>
    <td><%= staff.lname %></td>
    <td><%= staff.address %></td>
    <td><%= staff.phone %></td>
    <td><%= staff.dob %></td>
    <td><%= link_to image_tag("icon-view.png", :border => 0), staff %></td>
    <td><%= link_to image_tag("pencil.png", :border => 0), edit_staff_path(staff) %></td>
    <td><%= link_to image_tag("icon_missing.png", :border => 0), staff, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>


<br />
<%= will_paginate @posts %> <br />
<div align='center'>

<%= link_to 'New Staff', new_staff_path %> |
<%= link_to 'Back', :controller => 'admin',  :action => "index" %>

</div>

app/views/staffs/new.html.erb
<h1 align='center'>New staff</h1>

<%= render 'form' %>
<div align='center'>
<%= link_to 'Back', staffs_path %>
</div>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

 <table id='tab1' cellpadding='5' align=center>
 <tr><td>First Name:</td>
<td>  <%= @staff.fname %></td>
<tr>
 <td>Last Name:</td>
  <td><%= @staff.lname %></td>
</tr>
<tr>
<td>Address:</td>
 <td> <%= @staff.address %></td>
</tr>
<tr>
<td>Phone:</td>
 <td> <%= @staff.phone %></td>
</tr>
<tr>
<td>Joining Date:</td>
 <td> <%= @staff.dob %></td>
</tr>
</table>

<div align='center'>
<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>
</div>