config/routes.rb
SchoolMgmt::Application.routes.draw do

  devise_for :users 

  resources :photos

  resources :contacts

  get "imggallery/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :aboutus
  resources :imggallery

  resources :staffs

  
   
  match 'home/about_us' => 'home#about_us'

 resources :class_mstrs
 resources :students
 resources :admin
 resources :adminhome
 resources :users   

 root :to => 'home#index'

 match "/index" =>  'home#index'

end

app/models/aboutu.rb
class Aboutu < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/class_mstr.rb
class ClassMstr < ActiveRecord::Base
  attr_accessible :class_name, :no_of_student, :teacher_name
  validates_presence_of :class_name
  validates_presence_of :teacher_name
  validates_presence_of :no_of_student
 
def self.search(search)
  if search
    where('class_name LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :gmaps, :latitude, :longitude, :name
acts_as_gmappable

  def gmaps4rails_address
   address
  end

  def gmaps4rails_infowindow
   "<h1>#{name}</h1>"
  end


 def gmaps4rails_sidebar
  name
 end

end

app/models/imggallery.rb
class Imggallery < ActiveRecord::Base
   attr_accessible :title, :body, :avatar
   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :name, :avatar

   has_attached_file :avatar, :styles => { :thumb => "100x100>", :large => "400x400>" }
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  attr_accessible :address, :dob, :fname, :lname, :phone

  def self.search(search)
  if search
    where('fname LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :address, :dob, :fname, :lname, :phone, :avatar
  validates_presence_of :fname
  validates_presence_of :lname
  validates_presence_of :address
  validates_presence_of :phone
  validates_presence_of :dob
  
  
  has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "100x100>" }


 def self.search(search)
  if search
    where('fname LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  #  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_role
  # attr_accessible :title, :body

  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

before_filter :authenticate_user!

def index
layout :adminheader  # looks for app/views/layouts/adminheader.html.erb

end
end

app/controllers/class_mstrs_controller.rb
class ClassMstrsController < ApplicationController
  # before_filter :authenticate_user!
  # GET /class_mstrs
  # GET /class_mstrs.json
  def index

    @class_mstrs = ClassMstr.search(params[:search]).paginate(:per_page => 5,  :page => params[ :page])
  end

  # GET /class_mstrs/1
  # GET /class_mstrs/1.json
  def show
    @class_mstr = ClassMstr.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @class_mstr }
    end
  end

  # GET /class_mstrs/new
  # GET /class_mstrs/new.json
  def new
    @class_mstr = ClassMstr.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @class_mstr }
    end
  end

  # GET /class_mstrs/1/edit
  def edit
    @class_mstr = ClassMstr.find(params[:id])
  end

  # POST /class_mstrs
  # POST /class_mstrs.json
  def create
    @class_mstr = ClassMstr.new(params[:class_mstr])

    respond_to do |format|
      if @class_mstr.save
        format.html { redirect_to @class_mstr, notice: 'Class mstr was successfully created.' }
        format.json { render json: @class_mstr, status: :created, location: @class_mstr }
      else
        format.html { render action: "new" }
        format.json { render json: @class_mstr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /class_mstrs/1
  # PUT /class_mstrs/1.json
  def update
    @class_mstr = ClassMstr.find(params[:id])

    respond_to do |format|
      if @class_mstr.update_attributes(params[:class_mstr])
        format.html { redirect_to @class_mstr, notice: 'Class mstr was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @class_mstr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_mstrs/1
  # DELETE /class_mstrs/1.json
  def destroy
    @class_mstr = ClassMstr.find(params[:id])
    @class_mstr.destroy

    respond_to do |format|
      format.html { redirect_to class_mstrs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 

  def about_us
   @aboutus = Aboutu.find(:all)
   respond_to do |format|
      format.html # about_us.html.erb
      format.json { render json: @aboutu }
   end
  end 

   def index
    @staff = Staff.find(:all)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @staff }
    end
  end

end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/adminhome_helper.rb
module AdminhomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_mstrs_helper.rb
module ClassMstrsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imggallery_helper.rb
module ImggalleryHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/class_mstrs/_form.html.erb
<%= form_for(@class_mstr) do |f| %>
  <% if @class_mstr.errors.any? %>
  <div id ='error' align='center'>
    <div id="error_explanation">
      <h2><%= pluralize(@class_mstr.errors.count, "error") %> prohibited this class_mstr from being saved:</h2>

      <ul>
      <% @class_mstr.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    </div>
  <% end %>

   <table id='tab2' cellpadding='5' align=center>
     <tr><td>
       <%= f.label :class_name %>
	 </td>
   <td>
    <%= f.text_field :class_name %>
 </td></tr>
  <tr><td>
    <%= f.label :teacher_name %>
  </td>
    <td><%= f.text_field :teacher_name %>
  </td></tr>
  
    <tr><td>
    <%= f.label :no_of_student %></td>
   <td> <%= f.text_field :no_of_student %></td></tr>
  <tr>
 <td colspan='2' align='center'>
  <div class="actions">
    <%= f.submit %>
  </div>
  </td>
 </tr>
 </table>
<% end %>

app/views/class_mstrs/edit.html.erb
<h1 align='center'> Edit Record</h1>

<%= render 'form' %>
<div align='center'>
<%= link_to 'Show', @class_mstr %> |
<%= link_to 'Back', class_mstrs_path %>
</div>

app/views/class_mstrs/index.html.erb
<h1 align='center'>Class Detail</h1>
<div align=left>
  <%= form_tag class_mstrs_path, method: :get do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search by name", fname: nil %>
  <% end %>
</div>

<table id='tab' border='1' cellpadding='5' align=center>
  <tr>
    <th>Class Code</th>
    <th>Class name</th>
    <th>Teacher name</th>
    <th>No of student</th>
    <th colspan='3'>Action</th>
    
  </tr>

<% @class_mstrs.each do |class_mstr| %>
  <tr>
     <td><%= class_mstr.id %></td>
    <td><%= class_mstr.class_name %></td>
    <td><%= class_mstr.teacher_name %></td>
    <td><%= class_mstr.no_of_student %></td>
    <td><%= link_to image_tag("icon-view.png", :border => 0), class_mstr %></td>
    <td><%= link_to image_tag("pencil.png", :border => 0), edit_class_mstr_path(class_mstr) %></td>
    <td><%= link_to image_tag("icon_missing.png", :border => 0), class_mstr, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>


<br/>
<%= will_paginate @posts %> <br />

<div align='center'>

<%= link_to 'New Class', new_class_mstr_path %> |
<%= link_to 'Back', :controller => 'admin', :class => "back_btn", :action => "index" %>
</div>

app/views/class_mstrs/new.html.erb
<h1 align='center'>Add new master</h1>

<%= render 'form' %>

<div align='center'>
<%= link_to 'Back', class_mstrs_path %>
</div>

app/views/class_mstrs/show.html.erb
<p id="notice"><%= notice %></p>
<h1 align='center'><%= @class_mstr.teacher_name %>'s detail</h1>
<table id='tab1' cellpadding='5' align=center>
<td>Class Code:</td>
 <td> <%= @class_mstr.id %></td></tr>
<tr>
<td>Class name:</td>
 <td> <%= @class_mstr.class_name %></td></tr>
 <tr>

<tr>
<td>
  Teacher name:</td>
  <td><%= @class_mstr.teacher_name %></tr></td>


<tr>
<td>
  No of student:</td>
 <td> <%= @class_mstr.no_of_student %></td></tr>
<tr>
<td align='center' colspan='2'>
<%= link_to 'Edit', edit_class_mstr_path(@class_mstr) %> |
<%= link_to 'Back', class_mstrs_path %>
</td>
</tr>
</table>