config/routes.rb
SchoolMgmt::Application.routes.draw do

  devise_for :users 

  resources :photos

  resources :contacts

  get "imggallery/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :aboutus
  resources :imggallery

  resources :staffs

  
   
  match 'home/about_us' => 'home#about_us'

 resources :class_mstrs
 resources :students
 resources :admin
 resources :adminhome
 resources :users   

 root :to => 'home#index'

 match "/index" =>  'home#index'

end

app/models/aboutu.rb
class Aboutu < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/class_mstr.rb
class ClassMstr < ActiveRecord::Base
  attr_accessible :class_name, :no_of_student, :teacher_name
  validates_presence_of :class_name
  validates_presence_of :teacher_name
  validates_presence_of :no_of_student
 
def self.search(search)
  if search
    where('class_name LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :gmaps, :latitude, :longitude, :name
acts_as_gmappable

  def gmaps4rails_address
   address
  end

  def gmaps4rails_infowindow
   "<h1>#{name}</h1>"
  end


 def gmaps4rails_sidebar
  name
 end

end

app/models/imggallery.rb
class Imggallery < ActiveRecord::Base
   attr_accessible :title, :body, :avatar
   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :name, :avatar

   has_attached_file :avatar, :styles => { :thumb => "100x100>", :large => "400x400>" }
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  attr_accessible :address, :dob, :fname, :lname, :phone

  def self.search(search)
  if search
    where('fname LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :address, :dob, :fname, :lname, :phone, :avatar
  validates_presence_of :fname
  validates_presence_of :lname
  validates_presence_of :address
  validates_presence_of :phone
  validates_presence_of :dob
  
  
  has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "100x100>" }


 def self.search(search)
  if search
    where('fname LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  #  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_role
  # attr_accessible :title, :body

  
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  # GET /aboutus
  # GET /aboutus.json
  def index
    @aboutus = Aboutu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aboutus }
    end
  end

  # GET /aboutus/1
  # GET /aboutus/1.json
  def show
    @aboutu = Aboutu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aboutu }
    end
  end

  # GET /aboutus/new
  # GET /aboutus/new.json
  def new
    @aboutu = Aboutu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aboutu }
    end
  end

  # GET /aboutus/1/edit
  def edit
    @aboutu = Aboutu.find(params[:id])
  end

  # POST /aboutus
  # POST /aboutus.json
  def create
    @aboutu = Aboutu.new(params[:aboutu])

    respond_to do |format|
      if @aboutu.save
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully created.' }
        format.json { render json: @aboutu, status: :created, location: @aboutu }
      else
        format.html { render action: "new" }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aboutus/1
  # PUT /aboutus/1.json
  def update
    @aboutu = Aboutu.find(params[:id])

    respond_to do |format|
      if @aboutu.update_attributes(params[:aboutu])
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aboutus/1
  # DELETE /aboutus/1.json
  def destroy
    @aboutu = Aboutu.find(params[:id])
    @aboutu.destroy

    respond_to do |format|
      format.html { redirect_to aboutus_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

before_filter :authenticate_user!

def index
layout :adminheader  # looks for app/views/layouts/adminheader.html.erb

end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 

  def about_us
   @aboutus = Aboutu.find(:all)
   respond_to do |format|
      format.html # about_us.html.erb
      format.json { render json: @aboutu }
   end
  end 

   def index
    @staff = Staff.find(:all)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @staff }
    end
  end

end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/adminhome_helper.rb
module AdminhomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_mstrs_helper.rb
module ClassMstrsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imggallery_helper.rb
module ImggalleryHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/aboutus/_form.html.erb
<%= form_for(@aboutu) do |f| %>
  <% if @aboutu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aboutu.errors.count, "error") %> prohibited this aboutu from being saved:</h2>

      <ul>
      <% @aboutu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aboutus/edit.html.erb
<h1>Editing aboutu</h1>

<%= render 'form' %>

<%= link_to 'Show', @aboutu %> |
<%= link_to 'Back', aboutus_path %>

app/views/aboutus/index.html.erb
<h1>Listing aboutus</h1>

<table>
  <tr>
    <th>Title</th>
    <th> </th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aboutus.each do |aboutu| %>
  <tr>
    <td><%= aboutu.title %></td>
    <td><%= aboutu.content %></td>
    <td><%= link_to 'Show', aboutu %></td>
    <td><%= link_to 'Edit', edit_aboutu_path(aboutu) %></td>
    <td><%= link_to 'Destroy', aboutu, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<% if @aboutus.count < 1 %> 
<%= link_to 'New Aboutu', new_aboutu_path %>
<% end %>

app/views/aboutus/new.html.erb
<h1>New aboutu</h1>

<%= render 'form' %>

<%= link_to 'Back', aboutus_path %>

app/views/aboutus/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Title:</b>
  <%= @aboutu.title %>
</p>
<p>
  <b>Content:</b>
  <%= @aboutu.content %>
</p>

<%= link_to 'Edit', edit_aboutu_path(@aboutu) %> |
<%= link_to 'Back', aboutus_path %>