config/routes.rb
SchoolMgmt::Application.routes.draw do

  devise_for :users 

  resources :photos

  resources :contacts

  get "imggallery/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :aboutus
  resources :imggallery

  resources :staffs

  
   
  match 'home/about_us' => 'home#about_us'

 resources :class_mstrs
 resources :students
 resources :admin
 resources :adminhome
 resources :users   

 root :to => 'home#index'

 match "/index" =>  'home#index'

end

app/models/aboutu.rb
class Aboutu < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/class_mstr.rb
class ClassMstr < ActiveRecord::Base
  attr_accessible :class_name, :no_of_student, :teacher_name
  validates_presence_of :class_name
  validates_presence_of :teacher_name
  validates_presence_of :no_of_student
 
def self.search(search)
  if search
    where('class_name LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :gmaps, :latitude, :longitude, :name
acts_as_gmappable

  def gmaps4rails_address
   address
  end

  def gmaps4rails_infowindow
   "<h1>#{name}</h1>"
  end


 def gmaps4rails_sidebar
  name
 end

end

app/models/imggallery.rb
class Imggallery < ActiveRecord::Base
   attr_accessible :title, :body, :avatar
   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :name, :avatar

   has_attached_file :avatar, :styles => { :thumb => "100x100>", :large => "400x400>" }
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  attr_accessible :address, :dob, :fname, :lname, :phone

  def self.search(search)
  if search
    where('fname LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :address, :dob, :fname, :lname, :phone, :avatar
  validates_presence_of :fname
  validates_presence_of :lname
  validates_presence_of :address
  validates_presence_of :phone
  validates_presence_of :dob
  
  
  has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "100x100>" }


 def self.search(search)
  if search
    where('fname LIKE ?', "%#{search}%")
  else
    scoped
  end
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  #  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_role
  # attr_accessible :title, :body

  
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/adminhome_helper.rb
module AdminhomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_mstrs_helper.rb
module ClassMstrsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imggallery_helper.rb
module ImggalleryHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admin/about_us.erb

<%=stylesheet_link_tag "css"%>


<table>
<tr>
<td class="h3" valign="top">Overview</td>
                  </tr>
				                    <tr>
                    <td class="text pad" height="500" valign="top"><p class="h2">Mission Statement</p>
<p><span style="font-size: larger"><b><i>To achieve and sustain Leadership in Management Education, Research, Consultancy and Development.</i></b></span></p>
<p>&nbsp;</p>
<p>Foundation for Organizational Research and Education (FORE) is committed to the advancement of Management Education, Research, Training and Consultancy. Incorporated in 1981, as a non-profit institution, FORE has been working with industry and academia for developing new domains of managerial thought and education and contributing to building leaders in today's global business environment.</p>
<p class="marginT10">Located in the heart of South Delhi, FORE provides contextual learning and helps in the development of students as thinking professionals, who have the ability to meet the future challenges of tomorrow's corporate leaders. The programmes develop multiple skills including managerial decision-making, problem-solving, analytical reasoning, communications, creativity and innovation.</p>
<p class="marginT10">FORE takes pride in its professional and high-quality faculty, modern infrastructure, technology and resources- be it in the fields of General Management, Human Resource, Finance, Operations, Marketing, Information Technology, Economics and International Business.<br>
&nbsp;</p>
</table>

app/views/admin/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchoolMgmt</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%=stylesheet_link_tag "css"%>

  <%= csrf_meta_tags %>
 
 <div style="height:150px;background:#D0E3FD;width:830px;margin-left:auto;margin-right:auto;text-align:center;padding-top:50px;margin-top:100px;">
 <h1 align='center'> Welcome To Admin Panel </h1>
 </div>
 <br/>

</head>
<body>


<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %> 

<%= yield %>

</body>
</html>

app/views/layouts/adminheader.html.erb
<h1 align='center'> School management system</h1>

 
 <% if user_signed_in? %>
     <p class="menu">
     <%= link_to "Student Detail |", students_path %> 
     <%= link_to "Class Detail |", class_mstrs_path %> 
     <%= link_to "Staff Detail |", staffs_path %>
     <%= link_to 'New Student |', new_student_path %>
     <%= link_to 'New Staff |', new_staff_path %>
     <%= link_to 'New Class', new_class_mstr_path %>
     <%= link_to 'About Us', aboutus_path %>
     
     <%= link_to "Sign out", destroy_user_session_path, :class => "sign_out", :method => :delete %>
     </p>
 
  <% end %> 

app/views/layouts/application.html.erb
<html>
<head>


  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "css"%>
 <link href="themes/1/js-image-slider.css" rel="stylesheet" type="text/css" />
    <script src="themes/1/js-image-slider.js" type="text/javascript"></script>
    <link href="generic.css" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Abel|Satisfy' rel='stylesheet' type='text/css' />
<link href="default.css" rel="stylesheet" type="text/css" media="all" />
<!--[if IE 6]>
<link href="default_ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->
</head>
<body>
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1>Ideal Public School</h1>
			
			</div>
			<div id="menu">
				<ul>
					
					<li class="current_page_item"><%= link_to 'Home', :controller => "home", :action => "index"  %></li>
					<li><%= link_to 'About Us', :controller => "home", :action => "about_us"  %></li>
					<li><%= link_to 'Photos', :controller => "photos", :action => "index"  %></li>
					<li><%= link_to 'Contact Us', :controller => "contacts", :action => "index"  %></li>
				</ul>
			</div>
		</div>
	</div>

   <div  id="container">
   <% flash.each do |name, msg| %>
   <%= content_tag :div, msg, :id => "flash_#{name}" %>
   </div>
   <% end %>  

   <%= yield %>
<%= yield :scripts %> 
	
	<div id="page-wrapper">
		<div id="page">
			<div id="wide-content">
				
			</div>
		</div>
	</div>
	<div id="recent-news">
		<h2>Recent News</h2>
		<div id="rbox1">
			<p class="date">October 28, 2012</p>
			<p class="link"><a href="#">In posuere eleifend odio quisque semper augue mattis wisi maecenas ligula.</a></p>
			<p> Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Suspendisse dictum porta lectus. </p>
			<p class="button-style1"><a href="#">Read More</a></p>
		</div>
		<div id="rbox2">
			<p class="date">October 23, 2012</p>
			<p><a href="#">Pellentesque viverra vulputate enim. Aliquam erat volutpat convallis dictum. </a></p>
			<p>Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Suspendisse dictum porta lectus. Donec placerat odio.</p>
			<p class="button-style1"><a href="#">Read More</a></p>
		</div>
		<div id="rbox3">
			<p class="date">October 20, 2012</p>
			<p><a href="#">Suspendisse dictum porta lectus. Donec placerat odio vel elit. Nullam ante orci.</a></p>
			<p>Pellentesque viverra vulputate enim. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. </p>
			<p class="button-style1"><a href="#">Read More</a></p>
		</div>
		<div id="rbox4">
			<p class="date">October 18, 2012</p>
			<p><a href="#">Donec placerat odio vel elit. Nullam ante orci, pellentesque eget, tempus quis.</a></p>
			<p>In posuere eleifend odio quisque semper augue mattis wisi maecenas ligula. Pellentesque viverra vulputate enim.</p>
			<p class="button-style1"><a href="#">Read More</a></p>
		</div>
	</div>
	<div id="footer-wrapper">
		<div id="footer-content">
			<div id="fbox1">
				<h2>Aenean facilisis</h2>
				<ul class="style2">
					<li class="first"><a href="#">Maecenas luctus lectus at sapien</a></li>
					<li><a href="#">Donec dictum metus in sapien</a></li>
					<li><a href="#">Integer gravida nibh quis urna</a></li>
					<li><a href="#">Etiam posuere augue sit amet nisl</a></li>
					<li><a href="#">Mauris vulputate dolor sit amet nibh</a></li>
					<li><a href="#">Praesent scelerisque scelerisque erat</a></li>
				</ul>
				<p class="button-style"><a href="#">More Details</a></p>
			</div>
			<div id="fbox2">
				<h2>Fusce ultrices fringilla </h2>
				<p>Vivamus nisl nibh, iaculis vitae, viverra sit amet, ullamcorper vitae, turpis. Aliquam erat volutpat. Vestibulum dui sem, pulvinar sed, imperdiet nec, iaculis nec, leo.</p>
				<p><%= image_tag("img05.jpg", :alt => "activites") %></p>
				
				<p class="button-style"><a href="#">More Details</a></p>
			</div>
			<div id="fbox3">
				<h2>Maecenas lectus</h2>
				<ul class="style3">
					<li class="first"><%= image_tag("img02.jpg", :alt => "activites") %>
					
						<p>Nullam non wisi a sem eleifend. Donec mattis libero eget urna. </p>
						<p class="posted">October 28, 2002  |  (10 )  Comments</p>
					</li>
					<li>
					<%= image_tag("img03.jpg", :alt => "activites") %>
					
						<p>Nullam non wisi a sem eleifend. Donec mattis libero eget urna. </p>
						<p class="posted">October 21, 2002  |  (10 )  Comments</p>
					</li>
					<li>
					<%= image_tag("img04.jpg", :alt => "activites") %>
					
						<p>Nullam non wisi a sem eleifend. Donec mattis libero eget urna. </p>
						<p class="posted">October 19, 2002  |  (10 )  Comments</p>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<div id="footer">
	<p>Copyright (c) 2012 idealtechnologys.com All rights reserved. Design by <a href="http://www.idealtechnologys.com"><u>idealtechnologys</u></a>. Photos by <a href="http://google.com/">google</a>.</p>
</div>
</body>
</html>

